/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dataStructures;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    @Test void appHasAGreeting()
    {
        Integer i = 1;
        Integer j = -1;

        System.out.println(i.hashCode());
        System.out.println(j.hashCode());
    }
}
